version: "2"
linters:
  settings:
    cyclop:
      max-complexity: 7
      package-average: 5.0
    gocyclo:
      min-complexity: 7
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - err113
    - errcheck
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - usestdlibvars
