version: "2"
linters-settings:
  cyclop:
    max-complexity: 2
    package-average: 1.0
  gocyclo:
    min-complexity: 2
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - err113
    - errcheck
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - usestdlibvars
