version: "2"
linters:
  settings:
    copyloopvar:
      check-alias: true
    cyclop:
      max-complexity: 7
      package-average: 5.0
    errcheck:
      check-blank: true
      check-type-assertions: true
    gocritic:
      enable-all: true
    gocyclo:
      min-complexity: 7
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    iface:
      enable:
        - identical
        - unused
        - opaque
        - unexported
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errorlint
    - errname
    - exptostd
    - forbidigo
    - funcorder
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - gomodguard
    - gosec
    - govet
    - iface
    - ineffassign
    - intrange
    - iotamixing
    - mirror
    - misspell
    - mnd
    - modernize
    - musttag
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - unconvert
    - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
formatters:
  enable:
    - gci
    - gofmt
