version: "2"
linters:
  settings:
    copyloopvar:
      check-alias: true
    cyclop:
      max-complexity: 7
      package-average: 5.0
    gocritic:
      enable-all: true
    gocyclo:
      min-complexity: 7
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errorlint
    - errname
    - exptostd
    - forbidigo
    - funcorder
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - usestdlibvars
formatters:
  enable:
    - gci
    - gofmt
