version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - err113
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - usestdlibvars
